import { byId, byQuery, byQueryAll } from './helpers.js';

function createShellSelectors(sectionNav) {
  return {
    hero: byQuery('header.hero'),
    title: byId('pageTitle'),
    status: byId('status'),
    footerSource: byId('footerSource'),
    globalSearchBtn: byId('globalSearchBtn'),
    themeToggleBtn: byId('themeToggleBtn'),
    sectionNav,
    sectionNavLinks: byQueryAll('.section-nav__link'),
    scrollTopBtn: byId('scrollTopBtn'),
  };
}

function createOverviewTabSelectors() {
  return {
    tabSwitcher: byId('tabSwitcher'),
    tabButtons: byQueryAll('[data-tab-target]'),
    tabPanels: byQueryAll('[data-tab-panel]'),
    tabOverview: byId('tabOverview'),
    edNavButton: byId('edNavButton'),
    closeEdPanelBtn: byId('closeEdPanelBtn'),
    overviewPanel: byId('panelOverview'),
    edPanel: byId('panelEd'),
  };
}

function createKpiSelectors() {
  return {
    kpiHeading: byId('kpiHeading'),
    kpiSubtitle: byId('kpiSubtitle'),
    kpiDatePrev: byId('kpiDatePrev'),
    kpiDateInput: byId('kpiDateInput'),
    kpiDateNext: byId('kpiDateNext'),
    kpiDateClear: byId('kpiDateClear'),
    kpiSummary: byId('kpiSummary'),
    kpiGrid: byId('kpiGrid'),
    lastShiftHourlyChart: byId('lastShiftHourlyChart'),
    lastShiftHourlyContext: byId('lastShiftHourlyContext'),
    lastShiftHourlyLegend: byId('lastShiftHourlyLegend'),
    lastShiftHourlyMetricButtons: byQueryAll('[data-last-shift-metric]'),
    kpiControls: byQuery('.kpi-controls'),
    kpiFiltersForm: byId('kpiFiltersForm'),
    kpiWindow: byId('kpiWindow'),
    kpiShift: byId('kpiShift'),
    kpiArrival: byId('kpiArrival'),
    kpiArrivalButtons: byQueryAll('[data-kpi-arrival]'),
    kpiDisposition: byId('kpiDisposition'),
    kpiCardType: byId('kpiCardType'),
    kpiCardTypeButtons: byQueryAll('[data-kpi-card-type]'),
    kpiFiltersReset: byId('kpiFiltersReset'),
    kpiFiltersToggle: byId('kpiFiltersToggle'),
    kpiActiveInfo: byId('kpiActiveFilters'),
  };
}

function createChartsSelectors() {
  return {
    chartHeading: byId('chartHeading'),
    chartSubtitle: byId('chartSubtitle'),
    dailyCaption: byId('dailyChartLabel'),
    dailyCaptionContext: byId('dailyChartContext'),
    dowCaption: byId('dowChartTitle'),
    dowStayCaption: byId('dowStayChartTitle'),
    dowCaptionContext: byId('dowChartContext'),
    dowStayCaptionContext: byId('dowStayChartContext'),
    hourlyCaption: byId('hourlyChartTitle'),
    hourlyMetricLabel: byId('hourlyMetricLabel'),
    hourlyMetricButtons: byQueryAll('[data-hourly-metric]'),
    hourlyDepartmentLabel: byId('hourlyDepartmentLabel'),
    hourlyDepartmentInput: byId('hourlyDepartment'),
    hourlyDepartmentSuggestions: byId('hourlyDepartmentSuggestions'),
    hourlyDepartmentToggle: byId('hourlyDepartmentToggle'),
    hourlyCompareToggle: byId('hourlyCompareToggle'),
    hourlyCompareYearA: byId('hourlyCompareYearA'),
    hourlyCompareYearB: byId('hourlyCompareYearB'),
    hourlyCompareSeriesGroup: byQuery('.hourly-compare-series'),
    hourlyCompareSeriesButtons: byQueryAll('[data-hourly-compare-series]'),
    hourlyWeekdayLabel: byId('hourlyWeekdayLabel'),
    hourlyWeekdaySelect: byId('hourlyWeekday'),
    hourlyStayLabel: byId('hourlyStayLabel'),
    hourlyStaySelect: byId('hourlyStayBucket'),
    hourlyResetFilters: byId('hourlyResetFilters'),
    funnelCaption: byId('funnelChartTitle'),
    heatmapCaption: byId('arrivalHeatmapTitle'),
    heatmapContainer: byId('arrivalHeatmap'),
    heatmapMetricSelect: byId('heatmapMetric'),
    heatmapMetricLabel: byId('heatmapMetricLabel'),
    heatmapFilterArrival: byId('heatmapArrival'),
    heatmapFilterDisposition: byId('heatmapDisposition'),
    heatmapFilterCardType: byId('heatmapCardType'),
    heatmapYearSelect: byId('heatmapYear'),
    chartYearLabel: byId('chartYearLabel'),
    chartYearSelect: byId('chartYear'),
    chartYearGroup: byId('chartYearGroup'),
    chartPeriodButtons: byQueryAll('[data-chart-period]'),
    chartTimeScopeSummary: byId('chartTimeScopeSummary'),
    chartFiltersReset: byId('chartFiltersReset'),
    chartFiltersSummary: byId('chartFiltersSummary'),
    chartFiltersForm: byId('chartFiltersForm'),
    chartFilterArrival: byId('chartArrival'),
    chartFilterArrivalButtons: byQueryAll('[data-chart-arrival]'),
    chartFilterDisposition: byId('chartDisposition'),
    chartFilterDispositionButtons: byQueryAll('[data-chart-disposition]'),
    chartFilterCardType: byId('chartCardType'),
    chartFilterCardTypeButtons: byQueryAll('[data-chart-card-type]'),
    chartFilterCompareButtons: byQueryAll('[data-chart-compare-gmp]'),
    chartFilterCompareGmp: byId('chartCompareGmp'),
    chartsHospitalTableHeading: byId('chartsHospitalTableHeading'),
    chartsHospitalTableSubtitle: byId('chartsHospitalTableSubtitle'),
    chartsHospitalTableCaption: byId('chartsHospitalTableCaption'),
    chartsHospitalTableYearLabel: byId('chartsHospitalTableYearLabel'),
    chartsHospitalTableYear: byId('chartsHospitalTableYear'),
    chartsHospitalTableSearchLabel: byId('chartsHospitalTableSearchLabel'),
    chartsHospitalTableSearch: byId('chartsHospitalTableSearch'),
    chartsHospitalTableHint: byId('chartsHospitalTableHint'),
    chartsHospitalTableBody: byId('chartsHospitalTableBody'),
    chartsHospitalTableRoot: byId('chartsHospitalTableRoot'),
    chartsHospitalDeptTrendCard: byId('chartsHospitalDeptTrendCard'),
    chartsHospitalDeptTrendTitle: byId('chartsHospitalDeptTrendTitle'),
    chartsHospitalDeptTrendSubtitle: byId('chartsHospitalDeptTrendSubtitle'),
    chartsHospitalDeptTrendCanvas: byId('chartsHospitalDeptTrendCanvas'),
    chartsHospitalDeptTrendEmpty: byId('chartsHospitalDeptTrendEmpty'),
    chartCards: byQueryAll('.chart-grid .chart-card'),
    chartCopyButtons: byQueryAll('[data-chart-copy]'),
    chartDownloadButtons: byQueryAll('[data-chart-download]'),
    tableDownloadButtons: byQueryAll('[data-table-download]'),
  };
}

function createRecentAndSummariesSelectors() {
  return {
    recentHeading: byId('recentHeading'),
    recentSubtitle: byId('recentSubtitle'),
    recentCaption: byId('recentCaption'),
    recentTable: byId('recentTable'),
    monthlyHeading: byId('monthlyHeading'),
    monthlySubtitle: byId('monthlySubtitle'),
    monthlyCaption: byId('monthlyCaption'),
    monthlyTable: byId('monthlyTable'),
    yearlyHeading: byId('yearlyHeading'),
    yearlySubtitle: byId('yearlySubtitle'),
    yearlyCaption: byId('yearlyCaption'),
    yearlyTable: byId('yearlyTable'),
    summariesReportsHeading: byId('summariesReportsHeading'),
    summariesReportsSubtitle: byId('summariesReportsSubtitle'),
    summariesReportsYear: byId('summariesReportsYear'),
    summariesReportsTopN: byId('summariesReportsTopN'),
    summariesReportsMinGroupSize: byId('summariesReportsMinGroupSize'),
    referralHospitalizedByPspcSort: byId('referralHospitalizedByPspcSort'),
    summariesReportsCoverage: byId('summariesReportsCoverage'),
    summariesJumpNav: byQuery('.summaries-jump-nav'),
    summariesJumpLinks: byQueryAll('.summaries-jump-nav__link'),
    diagnosisChart: byId('diagnosisChart'),
    ageDiagnosisHeatmapChart: byId('ageDiagnosisHeatmapChart'),
    diagnosisInfo: byId('diagnosisInfo'),
    z769TrendChart: byId('z769TrendChart'),
    referralTrendChart: byId('referralTrendChart'),
    referralDispositionYearlyChart: byId('referralDispositionYearlyChart'),
    referralMonthlyHeatmapChart: byId('referralMonthlyHeatmapChart'),
    referralHospitalizedByPspcChart: byId('referralHospitalizedByPspcChart'),
    pspcCorrelationChart: byId('pspcCorrelationChart'),
    ageDistributionChart: byId('ageDistributionChart'),
    pspcDistributionChart: byId('pspcDistributionChart'),
    reportExportButtons: byQueryAll('[data-report-export]'),
  };
}

function createFeedbackSelectors() {
  return {
    feedbackHeading: byId('feedbackHeading'),
    feedbackSubtitle: byId('feedbackSubtitle'),
    feedbackDescription: byId('feedbackDescription'),
    feedbackFiltersSummary: byId('feedbackFiltersSummary'),
    feedbackRespondentFilter: byId('feedbackRespondentFilter'),
    feedbackRespondentLabel: byId('feedbackRespondentLabel'),
    feedbackRespondentChips: byId('feedbackRespondentChips'),
    feedbackLocationFilter: byId('feedbackLocationFilter'),
    feedbackLocationLabel: byId('feedbackLocationLabel'),
    feedbackLocationChips: byId('feedbackLocationChips'),
    feedbackFilterButtons: byQueryAll('[data-feedback-filter]'),
    feedbackCaption: byId('feedbackCaption'),
    feedbackCards: byId('feedbackCards'),
    feedbackTrendTitle: byId('feedbackTrendTitle'),
    feedbackTrendSubtitle: byId('feedbackTrendSubtitle'),
    feedbackTrendControls: byId('feedbackTrendControls'),
    feedbackTrendControlsLabel: byId('feedbackTrendControlsLabel'),
    feedbackTrendButtons: byQueryAll('[data-trend-months]'),
    feedbackTrendMetrics: byId('feedbackTrendMetrics'),
    feedbackTrendMetricsDropdown: byId('feedbackTrendMetricsDropdown'),
    feedbackTrendMetricsTriggerLabel: byId('feedbackTrendMetricsTriggerLabel'),
    feedbackTrendMetricsLabel: byId('feedbackTrendMetricsLabel'),
    feedbackTrendMetricButtons: byQueryAll('[data-trend-metric]'),
    feedbackTrendMultiToggle: byId('feedbackTrendMultiToggle'),
    feedbackTrendMetricsHint: byId('feedbackTrendMetricsHint'),
    feedbackTrendCompareControls: byId('feedbackTrendCompareControls'),
    feedbackTrendCompareButtons: byQueryAll('[data-trend-compare]'),
    feedbackTrendCompareSelect: byId('feedbackTrendCompareSelect'),
    feedbackTrendCompareLabel: byId('feedbackTrendCompareLabel'),
    feedbackTrendSummary: byId('feedbackTrendSummary'),
    feedbackTrendSkeleton: byId('feedbackTrendSkeleton'),
    feedbackTrendMessage: byId('feedbackTrendMessage'),
    feedbackTrendChart: byId('feedbackTrendChart'),
    feedbackTableWrapper: byQuery('.table-wrapper--feedback'),
    feedbackTable: byId('feedbackTable'),
    feedbackColumnMonth: byId('feedbackColumnMonth'),
    feedbackColumnResponses: byId('feedbackColumnResponses'),
    feedbackColumnOverall: byId('feedbackColumnOverall'),
    feedbackColumnDoctors: byId('feedbackColumnDoctors'),
    feedbackColumnNurses: byId('feedbackColumnNurses'),
    feedbackColumnAides: byId('feedbackColumnAides'),
    feedbackColumnWaiting: byId('feedbackColumnWaiting'),
    feedbackColumnContact: byId('feedbackColumnContact'),
  };
}

function createEdAndSectionSelectors() {
  return {
    edHeading: byId('edHeading'),
    edStatus: byId('edStatus'),
    edSearchInput: byId('edSearchInput'),
    gydytojaiSearch: byId('gydytojaiSearch'),
    edCards: byId('edCards'),
    edDispositionsTitle: byId('edDispositionsTitle'),
    edDispositionsChart: byId('edDispositionsChart'),
    edDispositionsMessage: byId('edDispositionsMessage'),
    edStandardSection: byId('edStandardSection'),
    recentSection: byQuery('[data-section="recent"]'),
    monthlySection: byQuery('[data-section="monthly"]'),
    yearlySection: byQuery('[data-section="yearly"]'),
    summariesReportsSection: byQuery('[data-section="summaries-reports"]'),
    feedbackSection: byQuery('[data-section="feedback"]'),
    compareToggle: byId('compareToggle'),
    compareCard: byId('compareCard'),
    compareSummary: byId('compareSummary'),
    compareClear: byId('compareClear'),
  };
}

export function createFullSelectors() {
  const sectionNav = byQuery('.section-nav');
  return {
    ...createShellSelectors(sectionNav),
    ...createOverviewTabSelectors(),
    ...createKpiSelectors(),
    ...createChartsSelectors(),
    ...createRecentAndSummariesSelectors(),
    ...createFeedbackSelectors(),
    ...createEdAndSectionSelectors(),
  };
}
