export function createDashboardState({
  defaultChartFilters,
  defaultKpiFilters,
  defaultFeedbackFilters,
  defaultHeatmapFilters,
  defaultHeatmapMetric,
  hourlyMetricArrivals,
  hourlyCompareSeriesAll,
}) {
  return {
    loading: false,
    queuedReload: false,
    hasLoadedOnce: false,
    charts: {
      daily: null,
      dow: null,
      dowStay: null,
      hourly: null,
      lastShiftHourly: null,
      funnel: null,
      feedbackTrend: null,
      edDispositions: null,
    },
    chartLib: null,
    usingFallback: false,
    lastErrorMessage: '',
    rawRecords: [],
    dailyStats: [],
    primaryRecords: [],
    primaryDaily: [],
    monthly: {
      all: [],
      window: [],
    },
    yearlyExpandedYears: [],
    summariesReportsYear: 'all',
    summariesReportsTopN: 15,
    summariesReportsMinGroupSize: 100,
    doctorsYear: 'all',
    doctorsTopN: 15,
    doctorsMinCases: 30,
    doctorsSort: 'volume_desc',
    doctorsSelected: '__top3__',
    doctorsArrivalFilter: 'all',
    doctorsDispositionFilter: 'all',
    doctorsShiftFilter: 'all',
    doctorsDiagnosisFilter: 'all',
    doctorsSearch: '',
    doctorsTableSort: 'count_desc',
    doctorsCoverage: { total: 0, withDoctor: 0, percent: 0 },
    summariesReferralPspcSort: 'desc',
    summariesReferralPspcMode: 'cross',
    summariesReferralPspcTrendPspc: '__top3__',
    summariesReportsCoverage: { total: 0, extended: 0, percent: 0 },
    summariesHistoricalRecordsCache: {
      recordsRef: null,
      records: [],
    },
    summariesReportsScopeCache: {
      recordsRef: null,
      byYear: new Map(),
    },
    summariesReportsComputationCache: {
      recordsRef: null,
      key: '',
      value: null,
    },
    summariesReportCharts: {
      diagnosisFrequency: null,
      ageDiagnosisHeatmap: null,
      z769Trend: null,
      referralTrend: null,
      referralDispositionYearly: null,
      referralMonthlyHeatmap: null,
      referralHospitalizedByPspc: null,
      pspcCorrelation: null,
      ageDistribution: null,
      pspcDistribution: null,
      sexDistribution: null,
    },
    doctorsCharts: {
      volume: null,
      los: null,
      hospital: null,
      mix: null,
      trend: null,
      scatter: null,
    },
    dataMeta: null,
    loadCounter: 0,
    chartPeriod: 30,
    chartYear: null,
    chartsHospitalTableYear: 'all',
    chartsHospitalTableSort: 'total_desc',
    chartsHospitalTableSearch: '',
    chartsHospitalTableDepartment: '',
    chartsHospitalDeptTrendChart: null,
    chartsHospitalDeptTrendKey: '',
    chartsHospitalTableStatsCache: {
      recordsRef: null,
      byYear: new Map(),
    },
    chartsHospitalTableWorkerAgg: null,
    heatmapMetric: defaultHeatmapMetric,
    heatmapFilters: defaultHeatmapFilters
      ? defaultHeatmapFilters()
      : { arrival: 'all', disposition: 'all', cardType: 'all' },
    heatmapYear: null,
    hourlyWeekday: 'all',
    hourlyStayBucket: 'all',
    hourlyMetric: hourlyMetricArrivals,
    hourlyDepartment: 'all',
    hourlyCompareEnabled: false,
    hourlyCompareYears: [],
    hourlyCompareSeries: hourlyCompareSeriesAll,
    hourlyYAxisSuggestedMax: null,
    hourlyYAxisSuggestedMin: null,
    hourlyDepartmentOptions: [],
    hourlyDepartmentSuggestIndex: -1,
    chartData: {
      baseDaily: [],
      baseRecords: [],
      dailyWindow: [],
      funnel: null,
      heatmap: null,
      filteredDaily: [],
      filteredRecords: [],
      filteredWindowRecords: [],
    },
    theme: 'light',
    fullscreen: false,
    activeTab: 'overview',
    compare: {
      active: false,
      selections: [],
    },
    contrastWarning: false,
    chartFilters: defaultChartFilters(),
    kpi: {
      filters: defaultKpiFilters(),
      records: [],
      daily: [],
      lastShiftHourly: null,
      lastShiftHourlyMetric: 'arrivals',
      selectedDate: null,
    },
    feedback: {
      summary: null,
      monthly: [],
      usingFallback: false,
      lastErrorMessage: '',
      trendWindow: 6,
      trendMetrics: ['overallAverage'],
      trendCompareMode: 'none',
      records: [],
      filteredRecords: [],
      filters: defaultFeedbackFilters(),
      filterOptions: { respondent: [], location: [] },
      commentRotation: { timerId: null, index: 0, entries: [] },
    },
    ed: {
      records: [],
      summary: null,
      dispositions: [],
      daily: [],
      usingFallback: false,
      lastErrorMessage: '',
      error: null,
      updatedAt: null,
      commentRotation: { timerId: null, index: 0, entries: [] },
    },
    feedbackMetricCarousel: {
      index: 0,
      intervalMs: 8000,
      timerId: null,
      metricCatalog: [],
    },
    edSearchQuery: '',
    edLastDisplayVariant: 'snapshot',
  };
}
