export function createDashboardState({
  defaultChartFilters,
  defaultKpiFilters,
  defaultFeedbackFilters,
  defaultHeatmapFilters,
  defaultHeatmapMetric,
  hourlyMetricArrivals,
  hourlyCompareSeriesAll,
}) {
  return {
    loading: false,
    queuedReload: false,
    hasLoadedOnce: false,
    charts: {
      daily: null,
      dow: null,
      dowStay: null,
      hourly: null,
      lastShiftHourly: null,
      funnel: null,
      feedbackTrend: null,
      edDispositions: null,
    },
    chartLib: null,
    usingFallback: false,
    lastErrorMessage: '',
    rawRecords: [],
    dailyStats: [],
    primaryRecords: [],
    primaryDaily: [],
    monthly: {
      all: [],
      window: [],
    },
    yearlyExpandedYears: [],
    summariesReportsYear: 'all',
    summariesReportsTopN: 15,
    summariesReportsMinGroupSize: 100,
    doctorsYear: 'all',
    doctorsTopN: 15,
    doctorsMinCases: 30,
    doctorsSort: 'volume_desc',
    doctorsArrivalFilter: 'all',
    doctorsDispositionFilter: 'all',
    doctorsShiftFilter: 'all',
    doctorsSpecialtyFilter: 'all',
    doctorsSearch: '',
    doctorsSearchDebounced: '',
    doctorsSearchDebounceTimer: null,
    doctorsTableSort: 'count_desc',
    doctorsSpecialtyTableSort: 'count_desc',
    doctorsChartsHiddenAliases: [],
    doctorsAnnualMetric: 'count',
    doctorsAnnualSort: 'latest_desc',
    doctorsAnnualTopN: 12,
    doctorsAnnualMinYearCount: 2,
    doctorsAnnualCardsChartRefs: {},
    doctorsAnnualSelected: [],
    doctorsAnnualSearchInput: '',
    doctorsAnnualAvailable: [],
    doctorsAnnualSuggestIndex: -1,
    doctorsSpecialtyAnnualMetric: 'count',
    doctorsSpecialtyAnnualSort: 'latest_desc',
    doctorsSpecialtyAnnualTopN: 6,
    doctorsSpecialtyAnnualMinYearCount: 2,
    doctorsSpecialtyAnnualCardsChartRefs: {},
    doctorsSpecialtyAnnualSelected: [],
    doctorsSpecialtyAnnualAvailable: [],
    gydytojaiFiltersAdvancedExpanded: false,
    gydytojaiActiveFiltersExpanded: false,
    gydytojaiSectionExpanded: {
      results: true,
      specialty: false,
      annual: false,
      charts: false,
    },
    gydytojaiAnnualSubview: 'doctor',
    gydytojaiChartsExpandedExtras: false,
    gydytojaiChartsDoctorTogglesExpanded: false,
    doctorsCoverage: { total: 0, withDoctor: 0, percent: 0 },
    doctorsSpecialtyValidation: {
      enabled: false,
      valid: false,
      groups: [],
      errors: [],
      warnings: [],
      coverage: null,
    },
    doctorsSpecialtyUiEnabled: false,
    doctorsComparisonModel: null,
    doctorsKpiBaselineModel: null,
    doctorsExportState: {},
    summariesReferralPspcSort: 'desc',
    summariesReferralPspcMode: 'cross',
    summariesReferralPspcTrendPspc: '__top3__',
    summariesReportsCoverage: { total: 0, extended: 0, percent: 0 },
    summariesHistoricalRecordsCache: {
      recordsRef: null,
      records: [],
    },
    summariesReportsScopeCache: {
      recordsRef: null,
      byYear: new Map(),
    },
    summariesReportsComputationCache: {
      recordsRef: null,
      key: '',
      value: null,
    },
    summariesReportsDerivedCache: {
      recordsRef: null,
      key: '',
      value: null,
    },
    summariesReportsLastRenderContext: null,
    summariesReportsSecondaryVisible: false,
    summariesReportsSecondaryVisibilityObserver: null,
    summariesReportsDeferredRenderToken: 0,
    summariesReportsSecondaryRenderScheduled: false,
    summariesReportsSecondaryRenderReason: 'controls',
    summariesReportsPrimaryRenderedAt: null,
    summariesReportsSecondaryCompletedAt: null,
    summariesReportCharts: {
      diagnosisFrequency: null,
      ageDiagnosisHeatmap: null,
      z769Trend: null,
      referralTrend: null,
      referralDispositionYearly: null,
      referralMonthlyHeatmap: null,
      referralHospitalizedByPspc: null,
      pspcCorrelation: null,
      ageDistribution: null,
      pspcDistribution: null,
      sexDistribution: null,
    },
    doctorsCharts: {
      volume: null,
      los: null,
      hospital: null,
      mix: null,
      scatter: null,
    },
    dataMeta: null,
    mainData: {
      recordsHydrationState: 'full',
      deferredHydrationToken: 0,
      deferredHydration: null,
    },
    loadCounter: 0,
    chartPeriod: 30,
    chartYear: null,
    chartsHospitalTableYear: 'all',
    chartsHospitalTableSort: 'total_desc',
    chartsHospitalTableSearch: '',
    chartsHospitalTableDepartment: '',
    chartsHospitalDeptTrendChart: null,
    chartsHospitalDeptTrendKey: '',
    chartsHospitalTableHasRendered: false,
    chartsHospitalTableVisibilityObserver: null,
    chartsSecondaryVisibilityObserver: null,
    chartsHospitalTableStatsCache: {
      recordsRef: null,
      byYear: new Map(),
    },
    chartsHospitalTableWorkerAgg: null,
    heatmapMetric: defaultHeatmapMetric,
    heatmapFilters: defaultHeatmapFilters
      ? defaultHeatmapFilters()
      : { arrival: 'all', disposition: 'all', cardType: 'all' },
    heatmapYear: null,
    hourlyWeekday: 'all',
    hourlyStayBucket: 'all',
    hourlyMetric: hourlyMetricArrivals,
    hourlyDepartment: 'all',
    hourlyCompareEnabled: false,
    hourlyCompareYears: [],
    hourlyCompareSeries: hourlyCompareSeriesAll,
    hourlyYAxisSuggestedMax: null,
    hourlyYAxisSuggestedMin: null,
    hourlyDepartmentOptions: [],
    hourlyDepartmentSuggestIndex: -1,
    chartData: {
      baseDaily: [],
      baseRecords: [],
      dailyWindow: [],
      funnel: null,
      heatmap: null,
      filteredDaily: [],
      filteredRecords: [],
      filteredWindowRecords: [],
      cache: {
        yearScoped: null,
        filtered: null,
        windowed: null,
        funnel: null,
        heatmap: null,
      },
      heatmapFilterCache: {
        recordsRef: null,
        byKey: new Map(),
      },
    },
    chartsStartupPhases: {
      primaryVisible: false,
      secondaryComplete: false,
      hospitalRendered: false,
    },
    chartsDeferredRenderToken: 0,
    chartsSecondaryRenderScheduled: false,
    chartsSecondaryRenderSignature: '',
    chartsHeatmapRenderSignature: '',
    chartsHourlyRenderSignature: '',
    chartsSecondaryRenderFrameId: null,
    chartsHospitalRenderScheduled: false,
    chartsHospitalRenderFrameId: null,
    chartsFirstVisibleAt: null,
    chartsSectionRenderFlags: {
      heatmapVisible: false,
      hourlyVisible: false,
      heatmapRendered: false,
      hourlyRendered: false,
      hospitalVisible: false,
    },
    chartsSectionsExpanded: {
      main: true,
      hospital: false,
    },
    chartsSubsectionsExpanded: {
      overview: true,
      hourly: false,
      heatmap: false,
    },
    theme: 'light',
    fullscreen: false,
    activeTab: 'overview',
    compare: {
      active: false,
      selections: [],
    },
    contrastWarning: false,
    chartFilters: defaultChartFilters(),
    kpi: {
      filters: defaultKpiFilters(),
      records: [],
      daily: [],
      lastShiftHourly: null,
      lastShiftHourlyMetric: 'arrivals',
      selectedDate: null,
      workerDatasetHandle: null,
      workerSummaryModeAvailableDateKeys: [],
      workerSummaryModeDateIndexMap: new Map(),
      workerSummaryModeSelectedDateRecordsKey: '',
      workerSummaryModeSelectedDateRecordsRefPrimary: null,
      workerSummaryModeSelectedDateRecords: [],
      workerSummaryModeSelectedDateDailyStats: [],
      workerSummaryModeSelectedDateRecordsLoadingKey: '',
      workerSummaryModeSelectedDateRecordsLoadingRefPrimary: null,
    },
    feedback: {
      summary: null,
      monthly: [],
      usingFallback: false,
      lastErrorMessage: '',
      trendWindow: 6,
      trendMetrics: ['overallAverage'],
      trendMultiMode: false,
      trendCompareMode: 'none',
      records: [],
      filteredRecords: [],
      filters: defaultFeedbackFilters(),
      filterOptions: { respondent: [], location: [] },
      commentRotation: { timerId: null, index: 0, entries: [] },
    },
    ed: {
      records: [],
      summary: null,
      dispositions: [],
      daily: [],
      usingFallback: false,
      lastErrorMessage: '',
      error: null,
      updatedAt: null,
      commentRotation: { timerId: null, index: 0, entries: [] },
    },
    feedbackMetricCarousel: {
      index: 0,
      intervalMs: 8000,
      timerId: null,
      metricCatalog: [],
    },
    edSearchQuery: '',
    edLastDisplayVariant: 'snapshot',
  };
}
