export function createDashboardState({
  defaultChartFilters,
  defaultKpiFilters,
  defaultFeedbackFilters,
  defaultHeatmapMetric,
  hourlyMetricArrivals,
  hourlyCompareSeriesAll,
}) {
  return {
    loading: false,
    queuedReload: false,
    hasLoadedOnce: false,
    charts: {
      daily: null,
      dow: null,
      dowStay: null,
      hourly: null,
      lastShiftHourly: null,
      funnel: null,
      feedbackTrend: null,
      edDispositions: null,
    },
    chartLib: null,
    usingFallback: false,
    lastErrorMessage: '',
    rawRecords: [],
    dailyStats: [],
    primaryRecords: [],
    primaryDaily: [],
    monthly: {
      all: [],
      window: [],
    },
    yearlyExpandedYears: [],
    dataMeta: null,
    loadCounter: 0,
    chartPeriod: 30,
    chartYear: null,
    heatmapMetric: defaultHeatmapMetric,
    hourlyWeekday: 'all',
    hourlyStayBucket: 'all',
    hourlyMetric: hourlyMetricArrivals,
    hourlyDepartment: 'all',
    hourlyCompareEnabled: false,
    hourlyCompareYears: [],
    hourlyCompareSeries: hourlyCompareSeriesAll,
    hourlyYAxisSuggestedMax: null,
    hourlyYAxisSuggestedMin: null,
    hourlyDepartmentOptions: [],
    hourlyDepartmentSuggestIndex: -1,
    chartData: {
      baseDaily: [],
      baseRecords: [],
      dailyWindow: [],
      funnel: null,
      heatmap: null,
      filteredDaily: [],
      filteredRecords: [],
      filteredWindowRecords: [],
    },
    theme: 'light',
    fullscreen: false,
    tvMode: false,
    activeTab: 'overview',
    compare: {
      active: false,
      selections: [],
    },
    contrastWarning: false,
    chartFilters: defaultChartFilters(),
    kpi: {
      filters: defaultKpiFilters(),
      records: [],
      daily: [],
      lastShiftHourly: null,
      lastShiftHourlyMetric: 'arrivals',
      selectedDate: null,
    },
    feedback: {
      summary: null,
      monthly: [],
      usingFallback: false,
      lastErrorMessage: '',
      trendWindow: 6,
      records: [],
      filteredRecords: [],
      filters: defaultFeedbackFilters(),
      filterOptions: { respondent: [], location: [] },
      commentRotation: { timerId: null, index: 0, entries: [] },
    },
    ed: {
      records: [],
      summary: null,
      dispositions: [],
      daily: [],
      usingFallback: false,
      lastErrorMessage: '',
      error: null,
      updatedAt: null,
      commentRotation: { timerId: null, index: 0, entries: [] },
    },
    edSearchQuery: '',
  };
}
