export function createSelectors() {
  return {
    hero: document.querySelector('header.hero'),
    title: document.getElementById('pageTitle'),
    tabSwitcher: document.getElementById('tabSwitcher'),
    tabButtons: Array.from(document.querySelectorAll('[data-tab-target]')),
    tabPanels: Array.from(document.querySelectorAll('[data-tab-panel]')),
    tabOverview: document.getElementById('tabOverview'),
    edNavButton: document.getElementById('edNavButton'),
    closeEdPanelBtn: document.getElementById('closeEdPanelBtn'),
    overviewPanel: document.getElementById('panelOverview'),
    edPanel: document.getElementById('panelEd'),
    status: document.getElementById('status'),
    footerSource: document.getElementById('footerSource'),
    kpiHeading: document.getElementById('kpiHeading'),
    kpiSubtitle: document.getElementById('kpiSubtitle'),
    kpiDatePrev: document.getElementById('kpiDatePrev'),
    kpiDateInput: document.getElementById('kpiDateInput'),
    kpiDateNext: document.getElementById('kpiDateNext'),
    kpiDateClear: document.getElementById('kpiDateClear'),
    kpiSummary: document.getElementById('kpiSummary'),
    kpiGrid: document.getElementById('kpiGrid'),
    lastShiftHourlyChart: document.getElementById('lastShiftHourlyChart'),
    lastShiftHourlyContext: document.getElementById('lastShiftHourlyContext'),
    lastShiftHourlyLegend: document.getElementById('lastShiftHourlyLegend'),
    lastShiftHourlyMetricButtons: Array.from(document.querySelectorAll('[data-last-shift-metric]')),
    chartHeading: document.getElementById('chartHeading'),
    chartSubtitle: document.getElementById('chartSubtitle'),
    dailyCaption: document.getElementById('dailyChartLabel'),
    dailyCaptionContext: document.getElementById('dailyChartContext'),
    dowCaption: document.getElementById('dowChartTitle'),
    dowStayCaption: document.getElementById('dowStayChartTitle'),
    dowCaptionContext: document.getElementById('dowChartContext'),
    dowStayCaptionContext: document.getElementById('dowStayChartContext'),
    hourlyCaption: document.getElementById('hourlyChartTitle'),
    hourlyMetricLabel: document.getElementById('hourlyMetricLabel'),
    hourlyMetricButtons: Array.from(document.querySelectorAll('[data-hourly-metric]')),
    hourlyDepartmentLabel: document.getElementById('hourlyDepartmentLabel'),
    hourlyDepartmentInput: document.getElementById('hourlyDepartment'),
    hourlyDepartmentSuggestions: document.getElementById('hourlyDepartmentSuggestions'),
    hourlyDepartmentToggle: document.getElementById('hourlyDepartmentToggle'),
    hourlyCompareToggle: document.getElementById('hourlyCompareToggle'),
    hourlyCompareYearA: document.getElementById('hourlyCompareYearA'),
    hourlyCompareYearB: document.getElementById('hourlyCompareYearB'),
    hourlyCompareSeriesGroup: document.querySelector('.hourly-compare-series'),
    hourlyCompareSeriesButtons: Array.from(document.querySelectorAll('[data-hourly-compare-series]')),
    hourlyWeekdayLabel: document.getElementById('hourlyWeekdayLabel'),
    hourlyWeekdaySelect: document.getElementById('hourlyWeekday'),
    hourlyStayLabel: document.getElementById('hourlyStayLabel'),
    hourlyStaySelect: document.getElementById('hourlyStayBucket'),
    hourlyResetFilters: document.getElementById('hourlyResetFilters'),
    funnelCaption: document.getElementById('funnelChartTitle'),
    heatmapCaption: document.getElementById('arrivalHeatmapTitle'),
    heatmapContainer: document.getElementById('arrivalHeatmap'),
    heatmapMetricSelect: document.getElementById('heatmapMetric'),
    heatmapMetricLabel: document.getElementById('heatmapMetricLabel'),
    heatmapFilterArrival: document.getElementById('heatmapArrival'),
    heatmapFilterDisposition: document.getElementById('heatmapDisposition'),
    heatmapFilterCardType: document.getElementById('heatmapCardType'),
    heatmapYearSelect: document.getElementById('heatmapYear'),
    chartYearLabel: document.getElementById('chartYearLabel'),
    chartYearSelect: document.getElementById('chartYear'),
    chartPeriodButtons: Array.from(document.querySelectorAll('[data-chart-period]')),
    chartFiltersSummary: document.getElementById('chartFiltersSummary'),
    chartFiltersForm: document.getElementById('chartFiltersForm'),
    chartFilterArrival: document.getElementById('chartArrival'),
    chartFilterArrivalButtons: Array.from(document.querySelectorAll('[data-chart-arrival]')),
    chartFilterDisposition: document.getElementById('chartDisposition'),
    chartFilterDispositionButtons: Array.from(document.querySelectorAll('[data-chart-disposition]')),
    chartFilterCardType: document.getElementById('chartCardType'),
    chartFilterCardTypeButtons: Array.from(document.querySelectorAll('[data-chart-card-type]')),
    chartFilterCompareGmp: document.getElementById('chartCompareGmp'),
    chartsHospitalTableHeading: document.getElementById('chartsHospitalTableHeading'),
    chartsHospitalTableSubtitle: document.getElementById('chartsHospitalTableSubtitle'),
    chartsHospitalTableCaption: document.getElementById('chartsHospitalTableCaption'),
    chartsHospitalTableYearLabel: document.getElementById('chartsHospitalTableYearLabel'),
    chartsHospitalTableYear: document.getElementById('chartsHospitalTableYear'),
    chartsHospitalTableSearchLabel: document.getElementById('chartsHospitalTableSearchLabel'),
    chartsHospitalTableSearch: document.getElementById('chartsHospitalTableSearch'),
    chartsHospitalTableHint: document.getElementById('chartsHospitalTableHint'),
    chartsHospitalTableBody: document.getElementById('chartsHospitalTableBody'),
    chartsHospitalTableRoot: document.getElementById('chartsHospitalTableRoot'),
    chartsHospitalDeptTrendCard: document.getElementById('chartsHospitalDeptTrendCard'),
    chartsHospitalDeptTrendTitle: document.getElementById('chartsHospitalDeptTrendTitle'),
    chartsHospitalDeptTrendSubtitle: document.getElementById('chartsHospitalDeptTrendSubtitle'),
    chartsHospitalDeptTrendCanvas: document.getElementById('chartsHospitalDeptTrendCanvas'),
    chartsHospitalDeptTrendEmpty: document.getElementById('chartsHospitalDeptTrendEmpty'),
    chartCards: Array.from(document.querySelectorAll('.chart-grid .chart-card')),
    chartCopyButtons: Array.from(document.querySelectorAll('[data-chart-copy]')),
    chartDownloadButtons: Array.from(document.querySelectorAll('[data-chart-download]')),
    tableDownloadButtons: Array.from(document.querySelectorAll('[data-table-download]')),
    recentHeading: document.getElementById('recentHeading'),
    recentSubtitle: document.getElementById('recentSubtitle'),
    recentCaption: document.getElementById('recentCaption'),
    recentTable: document.getElementById('recentTable'),
    monthlyHeading: document.getElementById('monthlyHeading'),
    monthlySubtitle: document.getElementById('monthlySubtitle'),
    monthlyCaption: document.getElementById('monthlyCaption'),
    monthlyTable: document.getElementById('monthlyTable'),
    yearlyHeading: document.getElementById('yearlyHeading'),
    yearlySubtitle: document.getElementById('yearlySubtitle'),
    yearlyCaption: document.getElementById('yearlyCaption'),
    yearlyTable: document.getElementById('yearlyTable'),
    summariesReportsHeading: document.getElementById('summariesReportsHeading'),
    summariesReportsSubtitle: document.getElementById('summariesReportsSubtitle'),
    summariesReportsYear: document.getElementById('summariesReportsYear'),
    summariesReportsTopN: document.getElementById('summariesReportsTopN'),
    summariesReportsMinGroupSize: document.getElementById('summariesReportsMinGroupSize'),
    referralHospitalizedByPspcSort: document.getElementById('referralHospitalizedByPspcSort'),
    summariesReportsCoverage: document.getElementById('summariesReportsCoverage'),
    diagnosisChart: document.getElementById('diagnosisChart'),
    ageDiagnosisHeatmapChart: document.getElementById('ageDiagnosisHeatmapChart'),
    diagnosisInfo: document.getElementById('diagnosisInfo'),
    z769TrendChart: document.getElementById('z769TrendChart'),
    referralTrendChart: document.getElementById('referralTrendChart'),
    referralDispositionYearlyChart: document.getElementById('referralDispositionYearlyChart'),
    referralMonthlyHeatmapChart: document.getElementById('referralMonthlyHeatmapChart'),
    referralHospitalizedByPspcChart: document.getElementById('referralHospitalizedByPspcChart'),
    pspcCorrelationChart: document.getElementById('pspcCorrelationChart'),
    ageDistributionChart: document.getElementById('ageDistributionChart'),
    pspcDistributionChart: document.getElementById('pspcDistributionChart'),
    sexDistributionChart: document.getElementById('sexDistributionChart'),
    reportExportButtons: Array.from(document.querySelectorAll('[data-report-export]')),
    feedbackHeading: document.getElementById('feedbackHeading'),
    feedbackSubtitle: document.getElementById('feedbackSubtitle'),
    feedbackDescription: document.getElementById('feedbackDescription'),
    feedbackFiltersSummary: document.getElementById('feedbackFiltersSummary'),
    feedbackRespondentFilter: document.getElementById('feedbackRespondentFilter'),
    feedbackRespondentLabel: document.getElementById('feedbackRespondentLabel'),
    feedbackRespondentChips: document.getElementById('feedbackRespondentChips'),
    feedbackLocationFilter: document.getElementById('feedbackLocationFilter'),
    feedbackLocationLabel: document.getElementById('feedbackLocationLabel'),
    feedbackLocationChips: document.getElementById('feedbackLocationChips'),
    feedbackFilterButtons: Array.from(document.querySelectorAll('[data-feedback-filter]')),
    feedbackCaption: document.getElementById('feedbackCaption'),
    feedbackCards: document.getElementById('feedbackCards'),
    feedbackTrendTitle: document.getElementById('feedbackTrendTitle'),
    feedbackTrendSubtitle: document.getElementById('feedbackTrendSubtitle'),
    feedbackTrendControls: document.getElementById('feedbackTrendControls'),
    feedbackTrendControlsLabel: document.getElementById('feedbackTrendControlsLabel'),
    feedbackTrendButtons: Array.from(document.querySelectorAll('[data-trend-months]')),
    feedbackTrendSummary: document.getElementById('feedbackTrendSummary'),
    feedbackTrendSkeleton: document.getElementById('feedbackTrendSkeleton'),
    feedbackTrendMessage: document.getElementById('feedbackTrendMessage'),
    feedbackTrendChart: document.getElementById('feedbackTrendChart'),
    feedbackTableWrapper: document.querySelector('.table-wrapper--feedback'),
    feedbackTable: document.getElementById('feedbackTable'),
    feedbackColumnMonth: document.getElementById('feedbackColumnMonth'),
    feedbackColumnResponses: document.getElementById('feedbackColumnResponses'),
    feedbackColumnOverall: document.getElementById('feedbackColumnOverall'),
    feedbackColumnDoctors: document.getElementById('feedbackColumnDoctors'),
    feedbackColumnNurses: document.getElementById('feedbackColumnNurses'),
    feedbackColumnAides: document.getElementById('feedbackColumnAides'),
    feedbackColumnWaiting: document.getElementById('feedbackColumnWaiting'),
    feedbackColumnContact: document.getElementById('feedbackColumnContact'),
    edHeading: document.getElementById('edHeading'),
    edStatus: document.getElementById('edStatus'),
    edSearchInput: document.getElementById('edSearchInput'),
    edCards: document.getElementById('edCards'),
    edDispositionsTitle: document.getElementById('edDispositionsTitle'),
    edDispositionsChart: document.getElementById('edDispositionsChart'),
    edDispositionsMessage: document.getElementById('edDispositionsMessage'),
    edStandardSection: document.getElementById('edStandardSection'),
    themeToggleBtn: document.getElementById('themeToggleBtn'),
    recentSection: document.querySelector('[data-section="recent"]'),
    monthlySection: document.querySelector('[data-section="monthly"]'),
    yearlySection: document.querySelector('[data-section="yearly"]'),
    summariesReportsSection: document.querySelector('[data-section="summaries-reports"]'),
    feedbackSection: document.querySelector('[data-section="feedback"]'),
    kpiControls: document.querySelector('.kpi-controls'),
    kpiFiltersForm: document.getElementById('kpiFiltersForm'),
    kpiWindow: document.getElementById('kpiWindow'),
    kpiShift: document.getElementById('kpiShift'),
    kpiArrival: document.getElementById('kpiArrival'),
    kpiArrivalButtons: Array.from(document.querySelectorAll('[data-kpi-arrival]')),
    kpiDisposition: document.getElementById('kpiDisposition'),
    kpiCardType: document.getElementById('kpiCardType'),
    kpiCardTypeButtons: Array.from(document.querySelectorAll('[data-kpi-card-type]')),
    kpiFiltersReset: document.getElementById('kpiFiltersReset'),
    kpiFiltersToggle: document.getElementById('kpiFiltersToggle'),
    kpiActiveInfo: document.getElementById('kpiActiveFilters'),
    compareToggle: document.getElementById('compareToggle'),
    compareCard: document.getElementById('compareCard'),
    compareSummary: document.getElementById('compareSummary'),
    compareClear: document.getElementById('compareClear'),
    sectionNav: document.querySelector('.section-nav'),
    sectionNavLinks: Array.from(document.querySelectorAll('.section-nav__link')),
    scrollTopBtn: document.getElementById('scrollTopBtn'),
  };
}

function byId(id) {
  return document.getElementById(id);
}

function byQuery(selector) {
  return document.querySelector(selector);
}

function byQueryAll(selector) {
  return Array.from(document.querySelectorAll(selector));
}

function byQueryIn(root, selector) {
  if (!root || !selector) {
    return null;
  }
  return root.querySelector(selector);
}

function byQueryAllIn(root, selector) {
  if (!root || !selector) {
    return [];
  }
  return Array.from(root.querySelectorAll(selector));
}

export function createSelectorsForPage(pageId) {
  const normalizedPage = typeof pageId === 'string' ? pageId.trim().toLowerCase() : '';

  if (normalizedPage === 'kpi') {
    const main = byQuery('main.container');
    const sectionNav = byQuery('.section-nav');
    const kpiSection = byQuery('[data-section="kpi"]');
    const kpiFiltersForm = byId('kpiFiltersForm');
    const kpiHourlyControls = byQueryIn(kpiSection, '.kpi-hourly-controls');
    return {
      hero: byQuery('header.hero'),
      title: byId('pageTitle'),
      status: byId('status'),
      footerSource: byId('footerSource'),
      themeToggleBtn: byId('themeToggleBtn'),
      scrollTopBtn: byId('scrollTopBtn'),
      sectionNav,
      sectionNavLinks: byQueryAllIn(sectionNav, '.section-nav__link'),
      kpiHeading: byId('kpiHeading'),
      kpiSubtitle: byId('kpiSubtitle'),
      kpiDatePrev: byId('kpiDatePrev'),
      kpiDateInput: byId('kpiDateInput'),
      kpiDateNext: byId('kpiDateNext'),
      kpiDateClear: byId('kpiDateClear'),
      kpiSummary: byId('kpiSummary'),
      kpiGrid: byId('kpiGrid'),
      kpiControls: byQueryIn(kpiSection, '.kpi-controls'),
      kpiFiltersForm,
      kpiWindow: byId('kpiWindow'),
      kpiShift: byId('kpiShift'),
      kpiArrival: byId('kpiArrival'),
      kpiArrivalButtons: byQueryAllIn(kpiFiltersForm, '[data-kpi-arrival]'),
      kpiDisposition: byId('kpiDisposition'),
      kpiCardType: byId('kpiCardType'),
      kpiCardTypeButtons: byQueryAllIn(kpiFiltersForm, '[data-kpi-card-type]'),
      kpiFiltersReset: byId('kpiFiltersReset'),
      kpiFiltersToggle: byId('kpiFiltersToggle'),
      kpiActiveInfo: byId('kpiActiveFilters'),
      lastShiftHourlyChart: byId('lastShiftHourlyChart'),
      lastShiftHourlyContext: byId('lastShiftHourlyContext'),
      lastShiftHourlyLegend: byId('lastShiftHourlyLegend'),
      lastShiftHourlyMetricButtons: byQueryAllIn(kpiHourlyControls, '[data-last-shift-metric]'),
      tableDownloadButtons: byQueryAllIn(main, '[data-table-download]'),
    };
  }

  if (normalizedPage === 'charts') {
    const main = byQuery('main.container');
    const sectionNav = byQuery('.section-nav');
    const chartSection = byQuery('[data-section="chart"]');
    const chartPeriodGroup = byId('chartPeriodGroup');
    const chartFiltersForm = byId('chartFiltersForm');
    const hourlyCompareSeriesGroup = byQueryIn(chartSection, '.hourly-compare-series');
    const chartsHospitalTableRoot = byId('chartsHospitalTableRoot');
    return {
      hero: byQuery('header.hero'),
      title: byId('pageTitle'),
      status: byId('status'),
      footerSource: byId('footerSource'),
      themeToggleBtn: byId('themeToggleBtn'),
      scrollTopBtn: byId('scrollTopBtn'),
      sectionNav,
      sectionNavLinks: byQueryAllIn(sectionNav, '.section-nav__link'),
      chartHeading: byId('chartHeading'),
      chartSubtitle: byId('chartSubtitle'),
      dailyCaption: byId('dailyChartLabel'),
      dailyCaptionContext: byId('dailyChartContext'),
      dowCaption: byId('dowChartTitle'),
      dowStayCaption: byId('dowStayChartTitle'),
      dowCaptionContext: byId('dowChartContext'),
      dowStayCaptionContext: byId('dowStayChartContext'),
      hourlyCaption: byId('hourlyChartTitle'),
      hourlyMetricLabel: byId('hourlyMetricLabel'),
      hourlyMetricButtons: byQueryAllIn(chartSection, '[data-hourly-metric]'),
      hourlyDepartmentLabel: byId('hourlyDepartmentLabel'),
      hourlyDepartmentInput: byId('hourlyDepartment'),
      hourlyDepartmentSuggestions: byId('hourlyDepartmentSuggestions'),
      hourlyDepartmentToggle: byId('hourlyDepartmentToggle'),
      hourlyCompareToggle: byId('hourlyCompareToggle'),
      hourlyCompareYearA: byId('hourlyCompareYearA'),
      hourlyCompareYearB: byId('hourlyCompareYearB'),
      hourlyCompareSeriesGroup,
      hourlyCompareSeriesButtons: byQueryAllIn(hourlyCompareSeriesGroup, '[data-hourly-compare-series]'),
      hourlyWeekdayLabel: byId('hourlyWeekdayLabel'),
      hourlyWeekdaySelect: byId('hourlyWeekday'),
      hourlyStayLabel: byId('hourlyStayLabel'),
      hourlyStaySelect: byId('hourlyStayBucket'),
      hourlyResetFilters: byId('hourlyResetFilters'),
      funnelCaption: byId('funnelChartTitle'),
      heatmapCaption: byId('arrivalHeatmapTitle'),
      heatmapContainer: byId('arrivalHeatmap'),
      heatmapMetricSelect: byId('heatmapMetric'),
      heatmapMetricLabel: byId('heatmapMetricLabel'),
      heatmapFilterArrival: byId('heatmapArrival'),
      heatmapFilterDisposition: byId('heatmapDisposition'),
      heatmapFilterCardType: byId('heatmapCardType'),
      heatmapYearSelect: byId('heatmapYear'),
      chartYearLabel: byId('chartYearLabel'),
      chartYearSelect: byId('chartYear'),
      chartPeriodButtons: byQueryAllIn(chartPeriodGroup, '[data-chart-period]'),
      chartFiltersSummary: byId('chartFiltersSummary'),
      chartFiltersForm,
      chartFilterArrival: byId('chartArrival'),
      chartFilterArrivalButtons: byQueryAllIn(chartFiltersForm, '[data-chart-arrival]'),
      chartFilterDisposition: byId('chartDisposition'),
      chartFilterDispositionButtons: byQueryAllIn(chartFiltersForm, '[data-chart-disposition]'),
      chartFilterCardType: byId('chartCardType'),
      chartFilterCardTypeButtons: byQueryAllIn(chartFiltersForm, '[data-chart-card-type]'),
      chartFilterCompareGmp: byId('chartCompareGmp'),
      chartsHospitalTableHeading: byId('chartsHospitalTableHeading'),
      chartsHospitalTableSubtitle: byId('chartsHospitalTableSubtitle'),
      chartsHospitalTableCaption: byId('chartsHospitalTableCaption'),
      chartsHospitalTableYearLabel: byId('chartsHospitalTableYearLabel'),
      chartsHospitalTableYear: byId('chartsHospitalTableYear'),
      chartsHospitalTableSearchLabel: byId('chartsHospitalTableSearchLabel'),
      chartsHospitalTableSearch: byId('chartsHospitalTableSearch'),
      chartsHospitalTableHint: byId('chartsHospitalTableHint'),
      chartsHospitalTableRoot,
      chartsHospitalTableHeaders: byQueryAllIn(chartsHospitalTableRoot, 'thead th'),
      chartsHospitalSortableHeaders: byQueryAllIn(chartsHospitalTableRoot, 'thead th[data-charts-hospital-sort]'),
      chartsHospitalTableBody: byId('chartsHospitalTableBody'),
      chartsHospitalDeptTrendCard: byId('chartsHospitalDeptTrendCard'),
      chartsHospitalDeptTrendTitle: byId('chartsHospitalDeptTrendTitle'),
      chartsHospitalDeptTrendSubtitle: byId('chartsHospitalDeptTrendSubtitle'),
      chartsHospitalDeptTrendCanvas: byId('chartsHospitalDeptTrendCanvas'),
      chartsHospitalDeptTrendEmpty: byId('chartsHospitalDeptTrendEmpty'),
      chartCards: byQueryAllIn(main, '.chart-grid .chart-card'),
      chartCopyButtons: byQueryAllIn(main, '[data-chart-copy]'),
      chartDownloadButtons: byQueryAllIn(main, '[data-chart-download]'),
      tableDownloadButtons: byQueryAllIn(main, '[data-table-download]'),
    };
  }

  if (normalizedPage === 'summaries') {
    const main = byQuery('main.container');
    const sectionNav = byQuery('.section-nav');
    return {
      hero: byQuery('header.hero'),
      title: byId('pageTitle'),
      status: byId('status'),
      footerSource: byId('footerSource'),
      themeToggleBtn: byId('themeToggleBtn'),
      scrollTopBtn: byId('scrollTopBtn'),
      sectionNav,
      sectionNavLinks: byQueryAllIn(sectionNav, '.section-nav__link'),
      yearlyTable: byId('yearlyTable'),
      summariesReportsHeading: byId('summariesReportsHeading'),
      summariesReportsSubtitle: byId('summariesReportsSubtitle'),
      summariesReportsYear: byId('summariesReportsYear'),
      summariesReportsTopN: byId('summariesReportsTopN'),
      summariesReportsMinGroupSize: byId('summariesReportsMinGroupSize'),
      referralHospitalizedByPspcSort: byId('referralHospitalizedByPspcSort'),
      summariesReportsCoverage: byId('summariesReportsCoverage'),
      diagnosisChart: byId('diagnosisChart'),
      ageDiagnosisHeatmapChart: byId('ageDiagnosisHeatmapChart'),
      diagnosisInfo: byId('diagnosisInfo'),
      z769TrendChart: byId('z769TrendChart'),
      referralTrendChart: byId('referralTrendChart'),
      referralDispositionYearlyChart: byId('referralDispositionYearlyChart'),
      referralMonthlyHeatmapChart: byId('referralMonthlyHeatmapChart'),
      referralHospitalizedByPspcChart: byId('referralHospitalizedByPspcChart'),
      pspcCorrelationChart: byId('pspcCorrelationChart'),
      ageDistributionChart: byId('ageDistributionChart'),
      pspcDistributionChart: byId('pspcDistributionChart'),
      sexDistributionChart: byId('sexDistributionChart'),
      reportExportButtons: byQueryAllIn(main, '[data-report-export]'),
      tableDownloadButtons: byQueryAllIn(main, '[data-table-download]'),
      monthlyHeading: byId('monthlyHeading'),
      monthlySubtitle: byId('monthlySubtitle'),
      monthlyCaption: byId('monthlyCaption'),
      monthlyTable: byId('monthlyTable'),
      yearlyHeading: byId('yearlyHeading'),
      yearlySubtitle: byId('yearlySubtitle'),
      yearlyCaption: byId('yearlyCaption'),
    };
  }

  if (normalizedPage === 'recent') {
    const main = byQuery('main.container');
    const sectionNav = byQuery('.section-nav');
    return {
      hero: byQuery('header.hero'),
      title: byId('pageTitle'),
      status: byId('status'),
      footerSource: byId('footerSource'),
      themeToggleBtn: byId('themeToggleBtn'),
      scrollTopBtn: byId('scrollTopBtn'),
      sectionNav,
      sectionNavLinks: byQueryAllIn(sectionNav, '.section-nav__link'),
      tableDownloadButtons: byQueryAllIn(main, '[data-table-download]'),
      recentHeading: byId('recentHeading'),
      recentSubtitle: byId('recentSubtitle'),
      recentCaption: byId('recentCaption'),
      recentTable: byId('recentTable'),
      compareToggle: byId('compareToggle'),
      compareCard: byId('compareCard'),
      compareSummary: byId('compareSummary'),
      compareClear: byId('compareClear'),
      monthlyTable: null,
      yearlyTable: null,
    };
  }

  if (normalizedPage === 'feedback') {
    const main = byQuery('main.container');
    const sectionNav = byQuery('.section-nav');
    const feedbackFilters = byId('feedbackFilters');
    const feedbackTrendControls = byId('feedbackTrendControls');
    return {
      hero: byQuery('header.hero'),
      title: byId('pageTitle'),
      status: byId('status'),
      footerSource: byId('footerSource'),
      themeToggleBtn: byId('themeToggleBtn'),
      scrollTopBtn: byId('scrollTopBtn'),
      sectionNav,
      sectionNavLinks: byQueryAllIn(sectionNav, '.section-nav__link'),
      feedbackHeading: byId('feedbackHeading'),
      feedbackSubtitle: byId('feedbackSubtitle'),
      feedbackDescription: byId('feedbackDescription'),
      feedbackFiltersSummary: byId('feedbackFiltersSummary'),
      feedbackRespondentFilter: byId('feedbackRespondentFilter'),
      feedbackRespondentLabel: byId('feedbackRespondentLabel'),
      feedbackRespondentChips: byId('feedbackRespondentChips'),
      feedbackLocationFilter: byId('feedbackLocationFilter'),
      feedbackLocationLabel: byId('feedbackLocationLabel'),
      feedbackLocationChips: byId('feedbackLocationChips'),
      feedbackFilterButtons: byQueryAllIn(feedbackFilters, '[data-feedback-filter]'),
      feedbackCaption: byId('feedbackCaption'),
      feedbackCards: byId('feedbackCards'),
      feedbackTrendTitle: byId('feedbackTrendTitle'),
      feedbackTrendSubtitle: byId('feedbackTrendSubtitle'),
      feedbackTrendControls,
      feedbackTrendControlsLabel: byId('feedbackTrendControlsLabel'),
      feedbackTrendButtons: byQueryAllIn(feedbackTrendControls, '[data-trend-months]'),
      feedbackTrendSummary: byId('feedbackTrendSummary'),
      feedbackTrendSkeleton: byId('feedbackTrendSkeleton'),
      feedbackTrendMessage: byId('feedbackTrendMessage'),
      feedbackTrendChart: byId('feedbackTrendChart'),
      feedbackTableWrapper: byQuery('.table-wrapper--feedback'),
      feedbackTable: byId('feedbackTable'),
      chartCopyButtons: byQueryAllIn(main, '[data-chart-copy]'),
      chartDownloadButtons: byQueryAllIn(main, '[data-chart-download]'),
      tableDownloadButtons: byQueryAllIn(main, '[data-table-download]'),
    };
  }

  if (normalizedPage === 'ed') {
    const sectionNav = byQuery('.section-nav');
    return {
      hero: byQuery('header.hero'),
      title: byId('pageTitle'),
      status: byId('status'),
      footerSource: byId('footerSource'),
      themeToggleBtn: byId('themeToggleBtn'),
      scrollTopBtn: byId('scrollTopBtn'),
      sectionNav,
      sectionNavLinks: byQueryAllIn(sectionNav, '.section-nav__link'),
      edHeading: byId('edHeading'),
      edStatus: byId('edStatus'),
      edSearchInput: byId('edSearchInput'),
      edCards: byId('edCards'),
      edDispositionsTitle: byId('edDispositionsTitle'),
      edDispositionsChart: byId('edDispositionsChart'),
      edDispositionsMessage: byId('edDispositionsMessage'),
      edStandardSection: byId('edStandardSection'),
      footer: byQuery('footer'),
    };
  }

  return {
    hero: byQuery('header.hero'),
    title: byId('pageTitle'),
    status: byId('status'),
    footerSource: byId('footerSource'),
    themeToggleBtn: byId('themeToggleBtn'),
    scrollTopBtn: byId('scrollTopBtn'),
    sectionNav: byQuery('.section-nav'),
    sectionNavLinks: byQueryAll('.section-nav__link'),
  };
}
