const PUBLIC_METRIC = Object.freeze({
  version: 1,
  visibility: 'public',
});

function defineMetric(metric) {
  return {
    ...PUBLIC_METRIC,
    ...metric,
  };
}

function defineSummaryReportMetric({
  id,
  aggregationLevel = 'aggregate',
  label,
  description,
  dependency,
  order,
}) {
  return defineMetric({
    id,
    domain: 'summaries',
    aggregationLevel,
    valueType: 'text',
    unit: '',
    label,
    description,
    format: 'text',
    dependencies: [dependency],
    computeKey: 'reportModel',
    tags: ['summaries', 'report'],
    surfaces: ['summaries-report-card'],
    order,
  });
}

/**
 * @type {import('./catalog-types.js').MetricsCatalog}
 */
export const METRICS_CATALOG = {
  version: 1,
  metrics: [
    defineMetric({
      id: 'total',
      domain: 'kpi',
      aggregationLevel: 'shift',
      valueType: 'count',
      unit: 'pac.',
      label: 'Atvykę',
      description: 'Bendras pacientų skaičius paskutinėje pamainoje.',
      format: 'integer',
      dependencies: ['dailyStats.count'],
      computeKey: 'lastShiftSummaryMetric',
      tags: ['kpi', 'flow'],
      surfaces: ['kpi-card', 'recent-compare'],
      order: 10,
      surfaceMeta: {
        'recent-compare': {
          label: 'Pacientai',
        },
      },
    }),
    defineMetric({
      id: 'night',
      domain: 'kpi',
      aggregationLevel: 'shift',
      valueType: 'count',
      unit: 'pac.',
      label: 'Naktiniai',
      description: 'Naktį atvykusių pacientų skaičius paskutinėje pamainoje.',
      format: 'integer',
      dependencies: ['dailyStats.night'],
      computeKey: 'lastShiftSummaryMetric',
      tags: ['kpi', 'flow'],
      surfaces: ['kpi-card'],
      order: 20,
    }),
    defineMetric({
      id: 'avgTime',
      domain: 'kpi',
      aggregationLevel: 'shift',
      valueType: 'duration',
      unit: 'val.',
      label: 'Vid. trukmė',
      description: 'Vidutinė buvimo trukmė paskutinėje pamainoje.',
      format: 'oneDecimal',
      dependencies: ['dailyStats.avgTime', 'dailyStats.durations'],
      computeKey: 'lastShiftSummaryMetric',
      tags: ['kpi', 'efficiency'],
      surfaces: ['kpi-card', 'recent-compare'],
      order: 30,
      surfaceMeta: {
        'recent-compare': {
          label: 'Vid. buvimo trukmė (val.)',
        },
      },
    }),
    defineMetric({
      id: 'discharged',
      domain: 'kpi',
      aggregationLevel: 'shift',
      valueType: 'count',
      unit: 'pac.',
      label: 'Išleisti',
      description: 'Išleistų pacientų skaičius paskutinėje pamainoje.',
      format: 'integer',
      dependencies: ['dailyStats.discharged'],
      computeKey: 'lastShiftSummaryMetric',
      tags: ['kpi', 'outcome'],
      surfaces: ['kpi-card', 'heatmap'],
      order: 40,
    }),
    defineMetric({
      id: 'hospitalized',
      domain: 'kpi',
      aggregationLevel: 'shift',
      valueType: 'count',
      unit: 'pac.',
      label: 'Hospitalizuoti',
      description: 'Hospitalizuotų pacientų skaičius paskutinėje pamainoje.',
      format: 'integer',
      dependencies: ['dailyStats.hospitalized'],
      computeKey: 'lastShiftSummaryMetric',
      tags: ['kpi', 'outcome'],
      surfaces: ['kpi-card', 'heatmap'],
      order: 50,
      surfaceMeta: {
        heatmap: {
          label: 'Hospitalizacijų skaičius / d.',
          unit: 'pac./d.',
          description: 'hospitalizacijų (vid. per dieną)',
        },
      },
    }),
    defineMetric({
      id: 'arrivals',
      domain: 'charts',
      aggregationLevel: 'hourly',
      valueType: 'rate',
      unit: 'pac./d.',
      label: 'Atvykimų skaičius / d.',
      description: 'Vidutinis atvykimų skaičius per pasirinktą valandą ir savaitės dieną.',
      format: 'oneDecimal',
      dependencies: ['heatmap.metrics.arrivals'],
      computeKey: 'heatmapMetric',
      tags: ['charts', 'heatmap'],
      surfaces: ['heatmap'],
      order: 60,
      surfaceMeta: {
        heatmap: {
          label: 'Atvykimų skaičius / d.',
          unit: 'pac./d.',
          description: 'atvykimų (vid. per dieną)',
        },
      },
    }),
    defineMetric({
      id: 'discharges',
      domain: 'charts',
      aggregationLevel: 'hourly',
      valueType: 'rate',
      unit: 'pac./d.',
      label: 'Išleidimų skaičius / d.',
      description: 'Vidutinis išleidimų skaičius per pasirinktą valandą ir savaitės dieną.',
      format: 'oneDecimal',
      dependencies: ['heatmap.metrics.discharges'],
      computeKey: 'heatmapMetric',
      tags: ['charts', 'heatmap'],
      surfaces: ['heatmap'],
      order: 65,
      surfaceMeta: {
        heatmap: {
          label: 'Išleidimų skaičius / d.',
          unit: 'pac./d.',
          description: 'išleidimų (vid. per dieną)',
        },
      },
    }),
    defineMetric({
      id: 'avgDuration',
      domain: 'charts',
      aggregationLevel: 'hourly',
      valueType: 'duration',
      unit: 'val.',
      label: 'Vidutinė buvimo trukmė (val.)',
      description: 'Vidutinė buvimo trukmė per pasirinktą valandą ir savaitės dieną.',
      format: 'oneDecimal',
      dependencies: ['heatmap.metrics.avgDuration'],
      computeKey: 'heatmapMetric',
      tags: ['charts', 'heatmap', 'efficiency'],
      surfaces: ['heatmap'],
      order: 70,
      surfaceMeta: {
        heatmap: {
          label: 'Vidutinė buvimo trukmė (val.)',
          unit: 'val.',
          description: 'vidutinė buvimo trukmė (val.)',
        },
      },
    }),
    defineMetric({
      id: 'emsShare',
      domain: 'recent',
      aggregationLevel: 'daily',
      valueType: 'share',
      unit: 'p. d.',
      label: 'GMP dalis',
      description: 'GMP atvykimų dalis tarp visų atvykimų.',
      format: 'percent',
      dependencies: ['dailyStats.emsShare'],
      computeKey: 'recentMetric',
      tags: ['recent', 'flow'],
      surfaces: ['recent-compare'],
      order: 80,
      surfaceMeta: {
        'recent-compare': {
          label: 'GMP dalis',
        },
      },
    }),
    defineMetric({
      id: 'hospShare',
      domain: 'recent',
      aggregationLevel: 'daily',
      valueType: 'share',
      unit: 'p. d.',
      label: 'Hospitalizacijų dalis',
      description: 'Hospitalizacijų dalis tarp visų atvykimų.',
      format: 'percent',
      dependencies: ['dailyStats.hospShare'],
      computeKey: 'recentMetric',
      tags: ['recent', 'outcome'],
      surfaces: ['recent-compare'],
      order: 90,
      surfaceMeta: {
        'recent-compare': {
          label: 'Hospitalizacijų dalis',
        },
      },
    }),
    defineSummaryReportMetric({
      id: 'summaries.diagnosis',
      label: 'Diagnozių pasiskirstymas pagal dažnį',
      description: 'TOP diagnozių grupių pasiskirstymas.',
      dependency: 'reports.diagnosis',
      order: 200,
    }),
    defineSummaryReportMetric({
      id: 'summaries.ageDiagnosisHeatmap',
      label: 'Amžiaus ir diagnozių grupių ryšys',
      description: 'Amžiaus grupių ir diagnozių pasiskirstymo šilumos žemėlapis.',
      dependency: 'reports.ageDiagnosisHeatmap',
      order: 210,
    }),
    defineSummaryReportMetric({
      id: 'summaries.z769Trend',
      aggregationLevel: 'yearly',
      label: 'Pasišalinę pacientai (Z76.9)',
      description: 'Diagnozės Z76.9 dalies dinamika per metus.',
      dependency: 'reports.z769Trend',
      order: 220,
    }),
    defineSummaryReportMetric({
      id: 'summaries.referralTrend',
      aggregationLevel: 'yearly',
      label: 'Pacientai su siuntimu',
      description: 'Pacientų su siuntimu dalies dinamika.',
      dependency: 'reports.referralTrend',
      order: 230,
    }),
    defineSummaryReportMetric({
      id: 'summaries.referralDispositionYearly',
      aggregationLevel: 'yearly',
      label: 'Siuntimas × baigtis pagal metus',
      description: 'Siuntimo ir gydymo baigties pasiskirstymas pagal metus.',
      dependency: 'reports.referralDispositionYearly',
      order: 240,
    }),
    defineSummaryReportMetric({
      id: 'summaries.referralMonthlyHeatmap',
      aggregationLevel: 'monthly',
      label: 'Siuntimų % pagal mėnesį',
      description: 'Siuntimų dalies dinamika mėnesių pjūvyje.',
      dependency: 'reports.referralMonthlyHeatmap',
      order: 250,
    }),
    defineSummaryReportMetric({
      id: 'summaries.referralHospitalizedByPspc',
      label: 'Hospitalizacijų dalis tarp pacientų su siuntimu pagal PSPC',
      description: 'PSPC pjūvio hospitalizacijų dalis pacientams su siuntimu.',
      dependency: 'reports.referralHospitalizedByPspc',
      order: 260,
    }),
    defineSummaryReportMetric({
      id: 'summaries.pspcCorrelation',
      label: 'PSPC: siuntimų ir hospitalizacijų ryšys',
      description: 'PSPC lygio siuntimų ir hospitalizacijų santykio analizė.',
      dependency: 'reports.pspcCorrelation',
      order: 270,
    }),
    defineSummaryReportMetric({
      id: 'summaries.ageDistribution',
      label: 'Pacientų pasiskirstymas pagal amžių',
      description: 'Pacientų pasiskirstymas pagal amžiaus grupes.',
      dependency: 'reports.ageDistribution',
      order: 280,
    }),
    defineSummaryReportMetric({
      id: 'summaries.pspcDistribution',
      label: 'Pacientų kiekiai pagal PSPC įstaigas',
      description: 'Pacientų pasiskirstymas pagal PSPC įstaigas.',
      dependency: 'reports.pspcDistribution',
      order: 290,
    }),
  ],
};
