/**
 * @type {import('./catalog-types.js').MetricsCatalog}
 */
export const METRICS_CATALOG = {
  version: 1,
  metrics: [
    {
      id: 'total',
      version: 1,
      domain: 'kpi',
      aggregationLevel: 'shift',
      valueType: 'count',
      unit: 'pac.',
      label: 'Atvykę',
      description: 'Bendras pacientų skaičius paskutinėje pamainoje.',
      format: 'integer',
      dependencies: ['dailyStats.count'],
      computeKey: 'lastShiftSummaryMetric',
      visibility: 'public',
      tags: ['kpi', 'flow'],
      surfaces: ['kpi-card', 'recent-compare'],
      order: 10,
      surfaceMeta: {
        'recent-compare': {
          label: 'Pacientai',
        },
      },
    },
    {
      id: 'night',
      version: 1,
      domain: 'kpi',
      aggregationLevel: 'shift',
      valueType: 'count',
      unit: 'pac.',
      label: 'Naktiniai',
      description: 'Naktį atvykusių pacientų skaičius paskutinėje pamainoje.',
      format: 'integer',
      dependencies: ['dailyStats.night'],
      computeKey: 'lastShiftSummaryMetric',
      visibility: 'public',
      tags: ['kpi', 'flow'],
      surfaces: ['kpi-card'],
      order: 20,
    },
    {
      id: 'avgTime',
      version: 1,
      domain: 'kpi',
      aggregationLevel: 'shift',
      valueType: 'duration',
      unit: 'val.',
      label: 'Vid. trukmė',
      description: 'Vidutinė buvimo trukmė paskutinėje pamainoje.',
      format: 'oneDecimal',
      dependencies: ['dailyStats.avgTime', 'dailyStats.durations'],
      computeKey: 'lastShiftSummaryMetric',
      visibility: 'public',
      tags: ['kpi', 'efficiency'],
      surfaces: ['kpi-card', 'recent-compare'],
      order: 30,
      surfaceMeta: {
        'recent-compare': {
          label: 'Vid. buvimo trukmė (val.)',
        },
      },
    },
    {
      id: 'discharged',
      version: 1,
      domain: 'kpi',
      aggregationLevel: 'shift',
      valueType: 'count',
      unit: 'pac.',
      label: 'Išleisti',
      description: 'Išleistų pacientų skaičius paskutinėje pamainoje.',
      format: 'integer',
      dependencies: ['dailyStats.discharged'],
      computeKey: 'lastShiftSummaryMetric',
      visibility: 'public',
      tags: ['kpi', 'outcome'],
      surfaces: ['kpi-card', 'heatmap'],
      order: 40,
    },
    {
      id: 'hospitalized',
      version: 1,
      domain: 'kpi',
      aggregationLevel: 'shift',
      valueType: 'count',
      unit: 'pac.',
      label: 'Hospitalizuoti',
      description: 'Hospitalizuotų pacientų skaičius paskutinėje pamainoje.',
      format: 'integer',
      dependencies: ['dailyStats.hospitalized'],
      computeKey: 'lastShiftSummaryMetric',
      visibility: 'public',
      tags: ['kpi', 'outcome'],
      surfaces: ['kpi-card', 'heatmap'],
      order: 50,
      surfaceMeta: {
        heatmap: {
          label: 'Hospitalizacijų skaičius / d.',
          unit: 'pac./d.',
          description: 'hospitalizacijų (vid. per dieną)',
        },
      },
    },
    {
      id: 'arrivals',
      version: 1,
      domain: 'charts',
      aggregationLevel: 'hourly',
      valueType: 'rate',
      unit: 'pac./d.',
      label: 'Atvykimų skaičius / d.',
      description: 'Vidutinis atvykimų skaičius per pasirinktą valandą ir savaitės dieną.',
      format: 'oneDecimal',
      dependencies: ['heatmap.metrics.arrivals'],
      computeKey: 'heatmapMetric',
      visibility: 'public',
      tags: ['charts', 'heatmap'],
      surfaces: ['heatmap'],
      order: 60,
      surfaceMeta: {
        heatmap: {
          label: 'Atvykimų skaičius / d.',
          unit: 'pac./d.',
          description: 'atvykimų (vid. per dieną)',
        },
      },
    },
    {
      id: 'discharges',
      version: 1,
      domain: 'charts',
      aggregationLevel: 'hourly',
      valueType: 'rate',
      unit: 'pac./d.',
      label: 'Išleidimų skaičius / d.',
      description: 'Vidutinis išleidimų skaičius per pasirinktą valandą ir savaitės dieną.',
      format: 'oneDecimal',
      dependencies: ['heatmap.metrics.discharges'],
      computeKey: 'heatmapMetric',
      visibility: 'public',
      tags: ['charts', 'heatmap'],
      surfaces: ['heatmap'],
      order: 65,
      surfaceMeta: {
        heatmap: {
          label: 'Išleidimų skaičius / d.',
          unit: 'pac./d.',
          description: 'išleidimų (vid. per dieną)',
        },
      },
    },
    {
      id: 'avgDuration',
      version: 1,
      domain: 'charts',
      aggregationLevel: 'hourly',
      valueType: 'duration',
      unit: 'val.',
      label: 'Vidutinė buvimo trukmė (val.)',
      description: 'Vidutinė buvimo trukmė per pasirinktą valandą ir savaitės dieną.',
      format: 'oneDecimal',
      dependencies: ['heatmap.metrics.avgDuration'],
      computeKey: 'heatmapMetric',
      visibility: 'public',
      tags: ['charts', 'heatmap', 'efficiency'],
      surfaces: ['heatmap'],
      order: 70,
      surfaceMeta: {
        heatmap: {
          label: 'Vidutinė buvimo trukmė (val.)',
          unit: 'val.',
          description: 'vidutinė buvimo trukmė (val.)',
        },
      },
    },
    {
      id: 'emsShare',
      version: 1,
      domain: 'recent',
      aggregationLevel: 'daily',
      valueType: 'share',
      unit: 'p. d.',
      label: 'GMP dalis',
      description: 'GMP atvykimų dalis tarp visų atvykimų.',
      format: 'percent',
      dependencies: ['dailyStats.emsShare'],
      computeKey: 'recentMetric',
      visibility: 'public',
      tags: ['recent', 'flow'],
      surfaces: ['recent-compare'],
      order: 80,
      surfaceMeta: {
        'recent-compare': {
          label: 'GMP dalis',
        },
      },
    },
    {
      id: 'hospShare',
      version: 1,
      domain: 'recent',
      aggregationLevel: 'daily',
      valueType: 'share',
      unit: 'p. d.',
      label: 'Hospitalizacijų dalis',
      description: 'Hospitalizacijų dalis tarp visų atvykimų.',
      format: 'percent',
      dependencies: ['dailyStats.hospShare'],
      computeKey: 'recentMetric',
      visibility: 'public',
      tags: ['recent', 'outcome'],
      surfaces: ['recent-compare'],
      order: 90,
      surfaceMeta: {
        'recent-compare': {
          label: 'Hospitalizacijų dalis',
        },
      },
    },
    {
      id: 'summaries.diagnosis',
      version: 1,
      domain: 'summaries',
      aggregationLevel: 'aggregate',
      valueType: 'text',
      unit: '',
      label: 'Diagnozių pasiskirstymas pagal dažnį',
      description: 'TOP diagnozių grupių pasiskirstymas.',
      format: 'text',
      dependencies: ['reports.diagnosis'],
      computeKey: 'reportModel',
      visibility: 'public',
      tags: ['summaries', 'report'],
      surfaces: ['summaries-report-card'],
      order: 200,
    },
    {
      id: 'summaries.ageDiagnosisHeatmap',
      version: 1,
      domain: 'summaries',
      aggregationLevel: 'aggregate',
      valueType: 'text',
      unit: '',
      label: 'Amžiaus ir diagnozių grupių ryšys',
      description: 'Amžiaus grupių ir diagnozių pasiskirstymo šilumos žemėlapis.',
      format: 'text',
      dependencies: ['reports.ageDiagnosisHeatmap'],
      computeKey: 'reportModel',
      visibility: 'public',
      tags: ['summaries', 'report'],
      surfaces: ['summaries-report-card'],
      order: 210,
    },
    {
      id: 'summaries.z769Trend',
      version: 1,
      domain: 'summaries',
      aggregationLevel: 'yearly',
      valueType: 'text',
      unit: '',
      label: 'Pasišalinę pacientai (Z76.9)',
      description: 'Diagnozės Z76.9 dalies dinamika per metus.',
      format: 'text',
      dependencies: ['reports.z769Trend'],
      computeKey: 'reportModel',
      visibility: 'public',
      tags: ['summaries', 'report'],
      surfaces: ['summaries-report-card'],
      order: 220,
    },
    {
      id: 'summaries.referralTrend',
      version: 1,
      domain: 'summaries',
      aggregationLevel: 'yearly',
      valueType: 'text',
      unit: '',
      label: 'Pacientai su siuntimu',
      description: 'Pacientų su siuntimu dalies dinamika.',
      format: 'text',
      dependencies: ['reports.referralTrend'],
      computeKey: 'reportModel',
      visibility: 'public',
      tags: ['summaries', 'report'],
      surfaces: ['summaries-report-card'],
      order: 230,
    },
    {
      id: 'summaries.referralDispositionYearly',
      version: 1,
      domain: 'summaries',
      aggregationLevel: 'yearly',
      valueType: 'text',
      unit: '',
      label: 'Siuntimas × baigtis pagal metus',
      description: 'Siuntimo ir gydymo baigties pasiskirstymas pagal metus.',
      format: 'text',
      dependencies: ['reports.referralDispositionYearly'],
      computeKey: 'reportModel',
      visibility: 'public',
      tags: ['summaries', 'report'],
      surfaces: ['summaries-report-card'],
      order: 240,
    },
    {
      id: 'summaries.referralMonthlyHeatmap',
      version: 1,
      domain: 'summaries',
      aggregationLevel: 'monthly',
      valueType: 'text',
      unit: '',
      label: 'Siuntimų % pagal mėnesį',
      description: 'Siuntimų dalies dinamika mėnesių pjūvyje.',
      format: 'text',
      dependencies: ['reports.referralMonthlyHeatmap'],
      computeKey: 'reportModel',
      visibility: 'public',
      tags: ['summaries', 'report'],
      surfaces: ['summaries-report-card'],
      order: 250,
    },
    {
      id: 'summaries.referralHospitalizedByPspc',
      version: 1,
      domain: 'summaries',
      aggregationLevel: 'aggregate',
      valueType: 'text',
      unit: '',
      label: 'Hospitalizacijų dalis tarp pacientų su siuntimu pagal PSPC',
      description: 'PSPC pjūvio hospitalizacijų dalis pacientams su siuntimu.',
      format: 'text',
      dependencies: ['reports.referralHospitalizedByPspc'],
      computeKey: 'reportModel',
      visibility: 'public',
      tags: ['summaries', 'report'],
      surfaces: ['summaries-report-card'],
      order: 260,
    },
    {
      id: 'summaries.pspcCorrelation',
      version: 1,
      domain: 'summaries',
      aggregationLevel: 'aggregate',
      valueType: 'text',
      unit: '',
      label: 'PSPC: siuntimų ir hospitalizacijų ryšys',
      description: 'PSPC lygio siuntimų ir hospitalizacijų santykio analizė.',
      format: 'text',
      dependencies: ['reports.pspcCorrelation'],
      computeKey: 'reportModel',
      visibility: 'public',
      tags: ['summaries', 'report'],
      surfaces: ['summaries-report-card'],
      order: 270,
    },
    {
      id: 'summaries.ageDistribution',
      version: 1,
      domain: 'summaries',
      aggregationLevel: 'aggregate',
      valueType: 'text',
      unit: '',
      label: 'Pacientų pasiskirstymas pagal amžių',
      description: 'Pacientų pasiskirstymas pagal amžiaus grupes.',
      format: 'text',
      dependencies: ['reports.ageDistribution'],
      computeKey: 'reportModel',
      visibility: 'public',
      tags: ['summaries', 'report'],
      surfaces: ['summaries-report-card'],
      order: 280,
    },
    {
      id: 'summaries.pspcDistribution',
      version: 1,
      domain: 'summaries',
      aggregationLevel: 'aggregate',
      valueType: 'text',
      unit: '',
      label: 'Pacientų kiekiai pagal PSPC įstaigas',
      description: 'Pacientų pasiskirstymas pagal PSPC įstaigas.',
      format: 'text',
      dependencies: ['reports.pspcDistribution'],
      computeKey: 'reportModel',
      visibility: 'public',
      tags: ['summaries', 'report'],
      surfaces: ['summaries-report-card'],
      order: 290,
    },
  ],
};
