import { byId, byQuery, byQueryAllIn, byQueryIn } from '../helpers.js';

export function createChartsPageSelectors() {
  const main = byQuery('main.container');
  const sectionNav = byQuery('.section-nav');
  const chartSection = byQuery('[data-section="chart"]');
  const chartPeriodGroup = byId('chartPeriodGroup');
  const chartFiltersForm = byId('chartFiltersForm');
  const hourlyCompareSeriesGroup = byQueryIn(chartSection, '.hourly-compare-series');
  const chartsJumpNav = byQueryIn(main, '.charts-jump-nav');
  const chartsHospitalTableRoot = byId('chartsHospitalTableRoot');

  return {
    hero: byQuery('header.hero'),
    title: byId('pageTitle'),
    status: byId('status'),
    footerSource: byId('footerSource'),
    themeToggleBtn: byId('themeToggleBtn'),
    scrollTopBtn: byId('scrollTopBtn'),
    sectionNav,
    sectionNavLinks: byQueryAllIn(sectionNav, '.section-nav__link'),
    chartHeading: byId('chartHeading'),
    chartSubtitle: byId('chartSubtitle'),
    dailyCaption: byId('dailyChartLabel'),
    dailyCaptionContext: byId('dailyChartContext'),
    dowCaption: byId('dowChartTitle'),
    dowStayCaption: byId('dowStayChartTitle'),
    dowCaptionContext: byId('dowChartContext'),
    dowStayCaptionContext: byId('dowStayChartContext'),
    hourlyCaption: byId('hourlyChartTitle'),
    hourlyMetricLabel: byId('hourlyMetricLabel'),
    hourlyMetricButtons: byQueryAllIn(chartSection, '[data-hourly-metric]'),
    hourlyDepartmentLabel: byId('hourlyDepartmentLabel'),
    hourlyDepartmentInput: byId('hourlyDepartment'),
    hourlyDepartmentSuggestions: byId('hourlyDepartmentSuggestions'),
    hourlyDepartmentToggle: byId('hourlyDepartmentToggle'),
    hourlyCompareToggle: byId('hourlyCompareToggle'),
    hourlyCompareYearA: byId('hourlyCompareYearA'),
    hourlyCompareYearB: byId('hourlyCompareYearB'),
    hourlyCompareSeriesGroup,
    hourlyCompareSeriesButtons: byQueryAllIn(hourlyCompareSeriesGroup, '[data-hourly-compare-series]'),
    hourlyWeekdayLabel: byId('hourlyWeekdayLabel'),
    hourlyWeekdaySelect: byId('hourlyWeekday'),
    hourlyStayLabel: byId('hourlyStayLabel'),
    hourlyStaySelect: byId('hourlyStayBucket'),
    hourlyResetFilters: byId('hourlyResetFilters'),
    funnelCaption: byId('funnelChartTitle'),
    heatmapCaption: byId('arrivalHeatmapTitle'),
    heatmapContainer: byId('arrivalHeatmap'),
    heatmapMetricSelect: byId('heatmapMetric'),
    heatmapMetricLabel: byId('heatmapMetricLabel'),
    heatmapFilterArrival: byId('heatmapArrival'),
    heatmapFilterDisposition: byId('heatmapDisposition'),
    heatmapFilterCardType: byId('heatmapCardType'),
    heatmapYearSelect: byId('heatmapYear'),
    chartYearLabel: byId('chartYearLabel'),
    chartYearSelect: byId('chartYear'),
    chartPeriodButtons: byQueryAllIn(chartPeriodGroup, '[data-chart-period]'),
    chartFiltersSummary: byId('chartFiltersSummary'),
    chartFiltersForm,
    chartFilterArrival: byId('chartArrival'),
    chartFilterArrivalButtons: byQueryAllIn(chartFiltersForm, '[data-chart-arrival]'),
    chartFilterDisposition: byId('chartDisposition'),
    chartFilterDispositionButtons: byQueryAllIn(chartFiltersForm, '[data-chart-disposition]'),
    chartFilterCardType: byId('chartCardType'),
    chartFilterCardTypeButtons: byQueryAllIn(chartFiltersForm, '[data-chart-card-type]'),
    chartFilterCompareGmp: byId('chartCompareGmp'),
    chartsJumpNav,
    chartsJumpLinks: byQueryAllIn(chartsJumpNav, '.charts-jump-nav__link'),
    chartsHospitalTableHeading: byId('chartsHospitalTableHeading'),
    chartsHospitalTableSubtitle: byId('chartsHospitalTableSubtitle'),
    chartsHospitalTableCaption: byId('chartsHospitalTableCaption'),
    chartsHospitalTableYearLabel: byId('chartsHospitalTableYearLabel'),
    chartsHospitalTableYear: byId('chartsHospitalTableYear'),
    chartsHospitalTableSearchLabel: byId('chartsHospitalTableSearchLabel'),
    chartsHospitalTableSearch: byId('chartsHospitalTableSearch'),
    chartsHospitalTableHint: byId('chartsHospitalTableHint'),
    chartsHospitalTableRoot,
    chartsHospitalTableHeaders: byQueryAllIn(chartsHospitalTableRoot, 'thead th'),
    chartsHospitalSortableHeaders: byQueryAllIn(
      chartsHospitalTableRoot,
      'thead th[data-charts-hospital-sort]'
    ),
    chartsHospitalTableBody: byId('chartsHospitalTableBody'),
    chartsHospitalDeptTrendCard: byId('chartsHospitalDeptTrendCard'),
    chartsHospitalDeptTrendTitle: byId('chartsHospitalDeptTrendTitle'),
    chartsHospitalDeptTrendSubtitle: byId('chartsHospitalDeptTrendSubtitle'),
    chartsHospitalDeptTrendCanvas: byId('chartsHospitalDeptTrendCanvas'),
    chartsHospitalDeptTrendEmpty: byId('chartsHospitalDeptTrendEmpty'),
    chartCards: byQueryAllIn(main, '.chart-grid .chart-card'),
    chartCopyButtons: byQueryAllIn(main, '[data-chart-copy]'),
    chartDownloadButtons: byQueryAllIn(main, '[data-chart-download]'),
    tableDownloadButtons: byQueryAllIn(main, '[data-table-download]'),
  };
}
