import { byId, byQuery, byQueryAllIn, byQueryIn, createPageShellSelectors } from '../helpers.js';

export function createGydytojaiPageSelectors() {
  const main = byQuery('main.container');
  const sectionNav = byQuery('.section-nav');
  const jumpNav = byQueryIn(main, '.gydytojai-jump-nav');

  return {
    ...createPageShellSelectors({ sectionNav }),
    gydytojaiHeading: byId('gydytojaiHeading'),
    gydytojaiSubtitle: byId('gydytojaiSubtitle'),
    gydytojaiCoverage: byId('gydytojaiCoverage'),
    gydytojaiLoadingInline: byId('gydytojaiLoadingInline'),
    gydytojaiLoadingState: byId('gydytojaiLoadingState'),
    gydytojaiFilterChips: byId('gydytojaiFilterChips'),
    gydytojaiFiltersAdvancedToggle: byId('gydytojaiFiltersAdvancedToggle'),
    gydytojaiFiltersAdvancedPanel: byId('gydytojaiFiltersAdvancedPanel'),
    gydytojaiYearChips: byId('gydytojaiYearChips'),
    gydytojaiTopNButtons: byQueryAllIn(main, '[data-gydytojai-topn]'),
    gydytojaiMinCasesButtons: byQueryAllIn(main, '[data-gydytojai-mincases]'),
    gydytojaiSortButtons: byQueryAllIn(main, '[data-gydytojai-sortby]'),
    gydytojaiArrivalButtons: byQueryAllIn(main, '[data-gydytojai-arrival]'),
    gydytojaiDispositionButtons: byQueryAllIn(main, '[data-gydytojai-disposition]'),
    gydytojaiShiftButtons: byQueryAllIn(main, '[data-gydytojai-shift]'),
    gydytojaiSpecialtyChips: byId('gydytojaiSpecialtyChips'),
    gydytojaiSpecialtyWarning: byId('gydytojaiSpecialtyWarning'),
    gydytojaiSearch: byId('gydytojaiSearch'),
    gydytojaiResetFilters: byId('gydytojaiResetFilters'),
    gydytojaiActiveFilters: byId('gydytojaiActiveFilters'),
    gydytojaiSpecialtySection: byId('gydytojaiSpecialtySection'),
    gydytojaiSpecialtySectionSummary: byId('gydytojaiSpecialtySectionSummary'),
    gydytojaiSpecialtyTable: byId('gydytojaiSpecialtyTable'),
    gydytojaiSpecialtyBody: byId('gydytojaiSpecialtyBody'),
    gydytojaiSpecialtyEmpty: byId('gydytojaiSpecialtyEmpty'),
    gydytojaiLeaderboardTable: byId('gydytojaiLeaderboardTable'),
    gydytojaiLeaderboardBody: byId('gydytojaiLeaderboardBody'),
    gydytojaiAnnualSection: byId('gydytojaiAnnualSection'),
    gydytojaiAnnualCombinedSection: byId('gydytojaiAnnualCombinedSection'),
    gydytojaiAnnualCombinedPanel: byId('gydytojaiAnnualCombinedSectionPanel'),
    gydytojaiAnnualSubview: byId('gydytojaiAnnualSubview'),
    gydytojaiAnnualSubviewButtons: byQueryAllIn(main, '[data-gydytojai-annual-subview]'),
    gydytojaiAnnualMetric: byId('gydytojaiAnnualMetric'),
    gydytojaiAnnualSort: byId('gydytojaiAnnualSort'),
    gydytojaiAnnualMetricButtons: byQueryAllIn(main, '[data-gydytojai-annual-metric]'),
    gydytojaiAnnualSortButtons: byQueryAllIn(main, '[data-gydytojai-annual-sort]'),
    gydytojaiAnnualDoctorInput: byId('gydytojaiAnnualDoctorInput'),
    gydytojaiAnnualSuggestions: byId('gydytojaiAnnualSuggestions'),
    gydytojaiAnnualAddDoctor: byId('gydytojaiAnnualAddDoctor'),
    gydytojaiAnnualClearDoctors: byId('gydytojaiAnnualClearDoctors'),
    gydytojaiAnnualSelectionHelp: byId('gydytojaiAnnualSelectionHelp'),
    gydytojaiAnnualSelected: byId('gydytojaiAnnualSelected'),
    gydytojaiAnnualCards: byId('gydytojaiAnnualCards'),
    gydytojaiAnnualEmpty: byId('gydytojaiAnnualEmpty'),
    gydytojaiSpecialtyAnnualSection: byId('gydytojaiSpecialtyAnnualSection'),
    gydytojaiSpecialtyAnnualMetric: byId('gydytojaiSpecialtyAnnualMetric'),
    gydytojaiSpecialtyAnnualSort: byId('gydytojaiSpecialtyAnnualSort'),
    gydytojaiSpecialtyAnnualMetricButtons: byQueryAllIn(main, '[data-gydytojai-specialty-annual-metric]'),
    gydytojaiSpecialtyAnnualSortButtons: byQueryAllIn(main, '[data-gydytojai-specialty-annual-sort]'),
    gydytojaiSpecialtyAnnualSelected: byId('gydytojaiSpecialtyAnnualSelected'),
    gydytojaiSpecialtyAnnualClear: byId('gydytojaiSpecialtyAnnualClear'),
    gydytojaiSpecialtyAnnualSummaryBody: byId('gydytojaiSpecialtyAnnualSummaryBody'),
    gydytojaiSpecialtyAnnualCards: byId('gydytojaiSpecialtyAnnualCards'),
    gydytojaiSpecialtyAnnualEmpty: byId('gydytojaiSpecialtyAnnualEmpty'),
    gydytojaiVolumeChart: byId('gydytojaiVolumeChart'),
    gydytojaiLosChart: byId('gydytojaiLosChart'),
    gydytojaiHospitalChart: byId('gydytojaiHospitalChart'),
    gydytojaiMixChart: byId('gydytojaiMixChart'),
    gydytojaiScatterChart: byId('gydytojaiScatterChart'),
    gydytojaiChartDoctorToggles: byId('gydytojaiChartDoctorToggles'),
    gydytojaiChartDoctorTogglesToggle: byId('gydytojaiChartDoctorTogglesToggle'),
    gydytojaiChartDoctorTogglesPanel: byId('gydytojaiChartDoctorTogglesPanel'),
    gydytojaiChartDoctorsReset: byId('gydytojaiChartDoctorsReset'),
    gydytojaiChartsMoreToggle: byId('gydytojaiChartsMoreToggle'),
    gydytojaiChartsMorePanel: byId('gydytojaiChartsMorePanel'),
    gydytojaiSectionToggleButtons: byQueryAllIn(main, '[data-gydytojai-section-toggle]'),
    gydytojaiSectionPanels: byQueryAllIn(main, '[data-gydytojai-section-panel]'),
    reportExportButtons: byQueryAllIn(main, '[data-report-export]'),
    tableDownloadButtons: byQueryAllIn(main, '[data-table-download]'),
    jumpNav,
    jumpLinks: byQueryAllIn(jumpNav, '.gydytojai-jump-nav__link'),
  };
}
